### PR TITLE
Add Rust documentation

### PR DESCRIPTION
**Pull request by LeSeulArtichaut**
> More documentations and references to come

Alright, let's do just that!

Add support for the official stable Rust documentation through the [List of all items](https://doc.rust-lang.org/stable/std/all.html) page.

### CODE REVIEW

**Comment by LeSeulArtichaut** [comment]
@FrenchMasterSword Are you going to merge this? Do I need to do additional work?

**Comment by Natendrtfm** [comment]
You didn't changed the docstring 
seems like a copy paste and you just changed the links

**Comment by LeSeulArtichaut** [comment]
Well of course it started with a copy-paste, which is not necessarily a bad thing if you don’t forget the docstring 😅
However, I didn’t « just change the links », I also changed the selection part which didn’t apply well on the Rust documentation

**Comment by LeSeulArtichaut** [comment]
@FrenchMasterSword Will you consider merging/reviewing this, or shall I close this PR?

**Pull request closed without merging**
